### ISSUE TITLE
Solr 4.x (DSpace 5.x) should use Java 8

### ISSUE THREAD

**Issue by alanorth** [1science/docker-dspace#2]
Solr developer [Shawn Heisey](https://wiki.apache.org/solr/ShawnHeisey) recommends using Java 8 with Solr 4.x, which is used by DSpace 5.

**Comment by jstlaurent** [comment]
Hi Alan. We're not using this image anymore. It was required for a side project that has since been abandoned. If you'd like, I could transfer ownership of the repo to you.

**Comment by alanorth** [comment]
Ok, good to know. No need to transfer it to me, I was only experimenting, but the Docker build time is an absolute nightmare because of the Maven build and lack of `~/.m2` cache, and I would never end up using it! Cheers!
